# http://www.appveyor.com/docs/appveyor-yml

# configuration for develop/CI and master/Release branch

branches:
  only:
    - dev
    - master

skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
test: off

pull_requests:
  do_not_increment_build_number: false

build_script:
  - ps: cd src
  - ps: .\build.ps1 -Target appveyor
  - ps: cd..

cache:
  - src\packages -> **\packages.config

artifacts:
  - path: \src\Publish\*.*

nuget:
  disable_publish_on_pr: true