# http://www.appveyor.com/docs/appveyor-yml

# configuration for develop/CI and master/Release branch

branches:
  only:
    - dev
    - master

skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
test: off

pull_requests:
  do_not_increment_build_number: false

install:
  # Install dotnet core 3.0 latest (alpha!!), as this is not provided on AppVeyor yet
  #- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe'
  #- ps: Start-Process .\dotnet-sdk-latest-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
  #- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/3.0.100-preview4-010538/dotnet-sdk-3.0.100-preview4-010538-win-x64.exe'
  #- ps: Start-Process .\dotnet-sdk-3.0.100-preview4-010538-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
  - ps: Start-FileDownload 'https://download.visualstudio.microsoft.com/download/pr/31b5b67f-b787-4f73-a728-5ec61f10a4de/be6430bcd9a62f610cd9f12f8cc2c736/dotnet-sdk-3.0.100-preview3-010431-win-x64.exe'
  - ps: Start-Process .\dotnet-sdk-3.0.100-preview3-010431-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait

build_script:
  - ps: cd src
  - ps: .\build.ps1 -Target appveyor
  - ps: cd..

cache:
  - src\packages -> **\packages.config

artifacts:
  - path: \src\Publish\*.*

nuget:
  disable_publish_on_pr: true